relative_permalink: false
permalink: none 
exclude: ["Gemfile","Gemfile.lock","newpost","notes.txt", "s3_website.yml"]
name: Askew's Stuff
description: David Askew's place on the web.
url: http://www.aske.ws
baseurl: http://www.aske.ws
highlighter: pygments
markdown: kramdown
encoding: utf-8
tag_page_layout: tag_page
tag_page_dir: tag
