#!/usr/bin/env ruby

unless ARGV[0]
  puts 'Usage: newpost "the post title"'
  exit(-1)
end

date_prefix = Time.now.strftime("%Y-%m-%d")
post_name = ARGV.join ' '
post_file_name = post_name.strip.downcase.gsub(/ /, '-')
post = "./_drafts/#{date_prefix}-#{post_file_name}.md"

header = <<-END
---
layout: post
tags: 
title: #{post_name}
category: post
---

Write the "#{post_name}" content here...
END

File.open(post, 'w') do |f|
  f << header
end

system("vim", post)

#credit : https://github.com/alexrothenberg/alexrothenberg.github.com/blob/master/_bin/newpost
